### PR TITLE
Bump uuid from 0.8.0 -> 1.0.0

### PR DESCRIPTION
**Pull request by kylewillmon**
This patch bumps the version of the uuid crate to 1.0.0. This is a
breaking change because uuid is used in the public interface of this
crate.

Ref: phylum-dev/cli#326

### CODE REVIEW

**Comment by cd-work** [comment]
I just noticed this, but is there a reason why `phylum-types` does not have any CI setup? Especially for PRs like these that wouldn't need any in-depth testing that would make reviews much easier.

**Comment by kylewillmon** [comment]
> I just noticed this, but is there a reason why `phylum-types` does not have any CI setup? Especially for PRs like these that wouldn't need any in-depth testing that would make reviews much easier.

Just because nobody has set it up yet, I believe.

**Comment by cd-work** [comment]
I've opened https://github.com/phylum-dev/phylum-types/issues/28 just in case I don't get to it today so it doesn't get lost over the weekend.

**Review by cd-work — APPROVED** [review]
Should be good after a rebase.

**Review by cd-work — DISMISSED** [review]

**Comment by kylewillmon** [comment]
The `uuid` crate is heavily used in `api`, so I will wait for approval from someone in @phylum-dev/user-components before merging this.

It looks like other dependencies for `api` are making this jump though, so it will be hitting that repo soon with or without this PR.

**Comment by matt-phylum** [comment]
I tried to compile api with this change. Rocket and sqlx are bringing in the old uuid and there are conflicts at least for sqlx. Relevant sqlx PR: launchbadge/sqlx#1821

**Comment by DanielJoyce** [comment]
This needs to hold off till we can update API for now.

**Review by samtay — APPROVED** [review]

**Pull request merged**
