### PR TITLE
Update submit package request

### PR DESCRIPTION
**Pull request by ejortega**
Update submission request

### CODE REVIEW

**Comment by matt-phylum** [comment]
Doesn't this change prevent the client from sending PURLs?

**Comment by ejortega** [comment]
> Doesn't this change prevent the client from sending PURLs?

The client is still currently sending PackageDescriptors. I made the change to PURL but updating it back to PackgeDescriptor with the the additional lockfile path so it can remain compatible with the CLI. In addition, updating the endpoint to accept the new descriptor.

**Comment by ejortega** [comment]
Can update to enum and accept both?

**Comment by matt-phylum** [comment]
Hmm I guess this is one of those cases where we're rolling back a change that was made to phylum-types, but also we're making a new change at the same time. The backend has its own definition of this struct which is JSON compatible and accepts both, so we're not actually losing any API capability here. It would be nice if the clients could send PURLs, but I guess that's unrelated to this change.

**Comment by ejortega** [comment]
Correct, I should have left it as PackageDescriptorAndLockfilePath in the first place, but it will remain compatible when CLI gets updated at some point.

**Review by matt-phylum — APPROVED** [review]

**Pull request merged**
