### PR TITLE
Add JSON Schema to types

### PR DESCRIPTION
**Pull request by mathew-horner**
This trait is required for types that we want to document with OpenAPI.

part of closing https://github.com/phylum-dev/api/issues/242

### CODE REVIEW

**Review by samtay — COMMENTED** [review]
The dependency and derivations could go behind a feature flag, since it's only used for `api`; not sure if this is worth optimizing at this point, given so few consumers of this library. Thoughts?

**Comment by mathew-horner** [comment]
> The dependency and derivations could go behind a feature flag, since it's only used for `api`; not sure if this is worth optimizing at this point, given so few consumers of this library. Thoughts?

I'm leaning towards no, personally. If compile times become a concern for this crate then we could probably revisit that, though.

**Review by cd-work — APPROVED** [review]
Seems pretty straight-forward. Only comment I can make is that the `schemars` dependency doesn't seem particularly well maintained but I don't see that being an immediate issue.

**Review by DanielJoyce — COMMENTED** [review]
Looks good, since all that is being done is adding another flag

**Pull request merged**
